// pub const ONE: &'static str = "1\u{fe0f}\u{20e3}";
// pub const TWO: &'static str = "2\u{fe0f}\u{20e3}";
// pub const THREE: &'static str = "3\u{fe0f}\u{20e3}";
// pub const FOUR: &'static str = "4\u{fe0f}\u{20e3}";
// pub const FIVE: &'static str = "5\u{fe0f}\u{20e3}";
// pub const YES_MARK: char = '✅';
pub const YES_CIRCLE: char = '🟢';
pub const NO_CIRCLE: char = '🔴';
pub const ASTENUTO_CIRCLE: char = '⚪';
